import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Activity, AlertTriangle, CheckCircle, Calendar } from 'lucide-react';
import { jsPDF } from 'jspdf';

const ReportSection = ({ result, onClose }) => {
    const [city, setCity] = useState('tunis');

    // Attempt to detect user location for smart booking
    useEffect(() => {
        fetch('https://ipapi.co/json/')
            .then(res => res.json())
            .then(data => {
                if (data && data.city) {
                    setCity(data.city.toLowerCase());
                }
            })
            .catch(err => console.log("Location detection failed, defaulting to Tunis"));
    }, []);

    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        const date = new Date().toLocaleString();

        // Header
        doc.setFillColor(11, 17, 32); // Dark blue background
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("PneumoDetect AI", 20, 25);
        doc.setFontSize(12);
        doc.text("Automated Diagnostic Report", 140, 25);

        // Context Info
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.text(`Report Date: ${date}`, 20, 50);
        doc.text(`Patient Reference: PT-${Math.floor(Math.random() * 10000)}`, 20, 55); // Mock Ref if empty

        // Result
        doc.setFontSize(16);
        doc.setTextColor(result.prediction === 'Pneumonia' ? 220 : 0, result.prediction === 'Pneumonia' ? 20 : 150, 60);
        doc.text(`Result: ${result.prediction.toUpperCase()}`, 20, 75);

        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Confidence Level: ${(result.confidence * 100).toFixed(2)}%`, 20, 85);

        doc.setLineWidth(0.5);
        doc.line(20, 95, 190, 95);

        // Disclaimer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("DISCLAIMER: This report is generated by an artificial intelligence system.", 20, 280);
        doc.text("It is NOT a final diagnosis. Please consult a qualified radiologist.", 20, 285);

        doc.save(`Pneumonia_Report_${Date.now()}.pdf`);
    };

    const handleBookDoctor = () => {
        // Construct standard URL structure for med.tn
        // med.tn/medecin/pneumologue/ville
        const bookingUrl = `https://www.med.tn/medecin/pneumologue/${city}`;
        window.open(bookingUrl, '_blank');
    };

    if (!result) return null;

    const confidence = result.confidence * 100;
    const isPneumonia = result.prediction === 'Pneumonia';

    return (
        <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 50 }}
            style={{
                position: 'fixed', top: 0, left: 0, width: '100%', height: '100vh',
                zIndex: 1000, background: 'rgba(11, 17, 32, 0.95)',
                overflowY: 'auto', backdropFilter: 'blur(10px)',
                padding: '40px 20px'
            }}
        >
            <div className="container" style={{ maxWidth: '900px', margin: '0 auto' }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '40px' }}>
                    <h2 style={{ fontSize: '2rem', fontWeight: '800' }}>Detailed Analysis Report</h2>
                    <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#94a3b8', fontSize: '1.2rem', cursor: 'pointer' }}>
                        Close X
                    </button>
                </div>

                {/* Main Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: 'minmax(300px, 2fr) 1fr', gap: '40px' }}>

                    {/* Left Column: Result & Confidence */}
                    <div>
                        <div className="glass-panel" style={{ padding: '30px', marginBottom: '30px', border: `1px solid ${isPneumonia ? 'var(--error-color)' : 'var(--success-color)'}` }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '20px' }}>
                                {isPneumonia ? <AlertTriangle size={32} color="var(--error-color)" /> : <CheckCircle size={32} color="var(--success-color)" />}
                                <h3 style={{ fontSize: '1.8rem', color: isPneumonia ? 'var(--error-color)' : 'var(--success-color)' }}>{result.prediction} Detected</h3>
                            </div>

                            <div style={{ marginBottom: '10px' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                                    <span>Confidence Level</span>
                                    <span>{confidence.toFixed(1)}%</span>
                                </div>
                                <div style={{ width: '100%', height: '10px', background: 'rgba(255,255,255,0.1)', borderRadius: '5px', overflow: 'hidden' }}>
                                    <div style={{ width: `${confidence}%`, height: '100%', background: isPneumonia ? 'var(--error-color)' : 'var(--success-color)', transition: 'width 1s ease' }}></div>
                                </div>
                            </div>
                            <p style={{ fontSize: '0.9rem', color: '#94a3b8', marginTop: '20px' }}>
                                The model has identified patterns consistent with {isPneumonia ? 'pneumonia' : 'normal tissue'} with high probability.
                            </p>
                        </div>

                        {/* Next Steps */}
                        <div style={{ marginBottom: '30px' }}>
                            <h3 style={{ marginBottom: '20px' }}>Recommended Clinical Actions</h3>
                            <div style={{ display: 'grid', gap: '15px' }}>
                                {isPneumonia ? (
                                    <>
                                        <ActionItem text="Immediate clinical correlation required." />
                                        <ActionItem text="Monitor Oxygen Saturation (SpO2)." />
                                        <div style={{ marginTop: '25px', padding: '20px', background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.15), rgba(30, 64, 175, 0.1))', borderRadius: '12px', border: '1px solid var(--accent-color)', boxShadow: '0 4px 20px rgba(56, 189, 248, 0.15)' }}>
                                            <h4 style={{ marginBottom: '15px', color: '#fff', display: 'flex', alignItems: 'center', gap: '10px', fontSize: '1.1rem' }}>
                                                <Calendar size={20} color="var(--accent-color)" />
                                                Schedule Specialist Consultation
                                            </h4>
                                            <p style={{ fontSize: '0.9rem', color: '#cbd5e1', marginBottom: '15px' }}>
                                                Connect with a top-rated pulmonologist in your area for immediate assistance.
                                            </p>

                                            <div style={{ display: 'flex', gap: '10px', flexDirection: 'column' }}>
                                                <label style={{ fontSize: '0.85rem', color: '#94a3b8' }}>Confirm Your City / Region:</label>
                                                <div style={{ display: 'flex', gap: '10px' }}>
                                                    <input
                                                        type="text"
                                                        value={city}
                                                        onChange={(e) => setCity(e.target.value)}
                                                        style={{
                                                            flex: 1, padding: '12px', borderRadius: '8px',
                                                            border: '1px solid rgba(255,255,255,0.1)',
                                                            background: 'rgba(0,0,0,0.3)', color: 'white',
                                                            outline: 'none'
                                                        }}
                                                        placeholder="Enter your city..."
                                                    />
                                                    <motion.button
                                                        whileHover={{ scale: 1.05 }}
                                                        whileTap={{ scale: 0.95 }}
                                                        onClick={handleBookDoctor}
                                                        style={{
                                                            padding: '12px 20px',
                                                            background: 'var(--accent-color)',
                                                            color: '#0b1120',
                                                            border: 'none',
                                                            borderRadius: '8px',
                                                            fontWeight: 'bold',
                                                            cursor: 'pointer',
                                                            whiteSpace: 'nowrap',
                                                            boxShadow: '0 0 15px rgba(56, 189, 248, 0.4)'
                                                        }}
                                                    >
                                                        Find Doctor
                                                    </motion.button>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                ) : (
                                    <>
                                        <ActionItem text="Routine follow-up as per standard protocol." />
                                        <ActionItem text="Monitor for symptom onset." />
                                    </>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* Right Column: Actions */}
                    <div>
                        <div className="glass-panel" style={{ padding: '30px', textAlign: 'center' }}>
                            <FileText size={48} color="var(--accent-color)" style={{ marginBottom: '20px' }} />
                            <h4 style={{ marginBottom: '10px' }}>Export Report</h4>
                            <p style={{ fontSize: '0.9rem', color: '#94a3b8', marginBottom: '20px' }}>Generate a PDF summary including the X-ray, prediction metrics, and timestamp.</p>
                            <button
                                onClick={handleDownloadPDF}
                                className="btn btn-primary"
                                style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px' }}
                            >
                                <Download size={18} /> Download PDF
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </motion.div>
    );
};

const ActionItem = ({ text }) => (
    <div style={{ padding: '15px', background: 'var(--secondary-bg)', borderRadius: '8px', borderLeft: '3px solid var(--accent-color)', display: 'flex', alignItems: 'center', gap: '10px' }}>
        <Activity size={18} color="var(--accent-color)" />
        {text}
    </div>
);

export default ReportSection;
